forum_modules/facebookauth/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from views import user_is_registered

urlpatterns = patterns('',
    url(r'^xd_receiver.htm$',  direct_to_template,  {'template': 'modules/facebookauth/xd_receiver.html'}, name='xd_receiver'),
    url(r'^facebook/user_is_registered/', user_is_registered, name="facebook_user_is_registered"),
)

forum_modules/robotstxt/urls.py
from django.conf.urls.defaults import *
from django.http import  HttpResponse
import settings

urlpatterns = patterns('',
    (r'^robots.txt$',  lambda r: HttpResponse(settings.ROBOTS_FILE.value)),
)

urls.py
from django.conf.urls.defaults import *
from django.utils.translation import ugettext as _
from django.conf import settings

urlpatterns = patterns('',
    (r'^%s' % settings.FORUM_SCRIPT_ALIAS, include('forum.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

forum/models/meta.py
from django.utils.translation import ugettext as _
from base import *

class Vote(models.Model):
    user = models.ForeignKey(User, related_name="votes")
    node = models.ForeignKey(Node, related_name="votes")
    value = models.SmallIntegerField()
    action = models.OneToOneField(Action, related_name="vote")
    voted_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        app_label = 'forum'
        unique_together = ('user', 'node')


class Flag(models.Model):
    user = models.ForeignKey(User, related_name="flags")
    node = models.ForeignKey(Node, related_name="flags")
    reason = models.CharField(max_length=300)
    action = models.OneToOneField(Action, related_name="flag")
    flagged_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        app_label = 'forum'
        unique_together = ('user', 'node')

class BadgesQuerySet(models.query.QuerySet):
    def get(self, *args, **kwargs):
        try:
            pk = [v for (k,v) in kwargs.items() if k in ('pk', 'pk__exact', 'id', 'id__exact')][0]
        except:
            return super(BadgesQuerySet, self).get(*args, **kwargs)

        from forum.badges.base import BadgesMeta
        badge = BadgesMeta.by_id.get(int(pk), None)
        if not badge:
            return super(BadgesQuerySet, self).get(*args, **kwargs)
        return badge.ondb


class BadgeManager(models.Manager):
    use_for_related_fields = True

    def get_query_set(self):
        return BadgesQuerySet(self.model)

class Badge(models.Model):
    GOLD = 1
    SILVER = 2
    BRONZE = 3

    type        = models.SmallIntegerField()
    cls         = models.CharField(max_length=50, null=True)
    awarded_count = models.PositiveIntegerField(default=0)
    
    awarded_to    = models.ManyToManyField(User, through='Award', related_name='badges')

    objects = BadgeManager()

    @property
    def name(self):
        cls = self.__dict__.get('_class', None)
        return cls and cls.name or _("Unknown")

    @property
    def description(self):
        cls = self.__dict__.get('_class', None)
        return cls and cls.description or _("No description available")

    @models.permalink
    def get_absolute_url(self):
        return ('badge', [], {'id': self.id, 'slug': slugify(self.name)})

    def save(self, *args, **kwargs):
        if isinstance(self.awarded_count, models.expressions.ExpressionNode):
            super(Badge, self).save(*args, **kwargs)
            self.awarded_count = self.__class__.objects.filter(id=self.id).values_list('awarded_count', flat=True)[0]
        else:
            super(Badge, self).save(*args, **kwargs)


    class Meta:
        app_label = 'forum'


class Award(models.Model):
    user = models.ForeignKey(User)
    badge = models.ForeignKey('Badge', related_name="awards")
    node = models.ForeignKey(Node, null=True)

    awarded_at = models.DateTimeField(default=datetime.datetime.now)

    trigger = models.ForeignKey(Action, related_name="awards", null=True)
    action = models.OneToOneField(Action, related_name="award")


    class Meta:
        unique_together = ('user', 'badge', 'node')
        app_label = 'forum'

forum/models/politician.py
'''
All models related to politician promise maker

Created on 19/12/2010

@author: Vaughan
'''
from base import *
from maker import Maker
from datetime import date
from datetime import datetime
from forum.models import *
from forum.models.tag import *

STATE_CHOICES = (
                      ('nsw', 'New South Wales'),
                      ('qld', 'Queensland'),
                      ('vic', 'Victoria'),
                      ('act', 'Australian Captial Territory'),
                      ('tas', 'Tasmania'),
                      )

GENDER_CHOICES = (
                       ('m','Male'),
                       ('f','Female'),
                       )

# remove null=true, this is just for testing importing
class Party(BaseModel):
    name = models.CharField(max_length=128,)
    short_name = models.CharField(max_length=128,blank=True, null=True)
    abbreviated_name = models.CharField(max_length=10)
    level = models.CharField(max_length=128,blank=True, null=True)
    region = models.CharField(max_length=128,blank=True, null=True)

    def __unicode__(self):
        return self.name

class Electorate(BaseModel):
    name = models.CharField(max_length=200)
    region = models.CharField(max_length=10, choices=STATE_CHOICES)

class Politician(Maker):
    party = models.ForeignKey(Party) # current party
    surname = models.CharField(max_length=128)
    firstname = models.CharField(max_length=128)
    constituency = models.ForeignKey(Electorate)
    promises = models.ManyToManyField('forum.Node', through='PromiseMaker')
    #add gender choice field

    @property
    def current_party(self):
        return Politician.party
    def all_promises(self):
        return self.node_set
    '''TODO: Must check that it is a questions'''
    @property
    def promise_count(self):
        return self.node_set.filter().count()
    @property
    def get_name(self):
        return self.name
    def __unicode__(self):
        return self.name

class PromiseMaker(BaseModel):
    #promise = models.ForeignKey('forum.NodeContent')
    revision = models.ForeignKey('forum.NodeRevision',null=True)
    promise = models.ForeignKey('forum.Node')
    maker = models.ForeignKey(Politician)

# maps portfolios to tags - use RegEx
class Portfolio(BaseModel):
    name = models.CharField(max_length=400)
    tags = models.ManyToManyField(Tag)

class PartyMember(BaseModel):
    politician = models.ForeignKey(Politician)
    party = models.ForeignKey(Party)
    date_joined = models.DateField(blank=True, null=True)
    date_left = models.DateField(blank=True, null=True)
    is_current = models.BooleanField()
    is_sitting = models.BooleanField()

    def __unicode__(self):
        return self.party.name + " " + self.politician.name

# maps party-members to parlimentary titles
class PartyMemberTitle(BaseModel):
    party_member = models.ForeignKey(PartyMember)
    date_from = models.DateField(blank=True, null=True)
    date_to = models.DateField(blank=True, null=True)
    portfolios = models.ManyToManyField(Portfolio)
    name = models.CharField(max_length=400)
    position = models.CharField(max_length=200,blank=True, null=True) # Minister,Special Minister
    
    def __unicode__(self):
        return self.name
    

class Election(BaseModel):
    name = models.CharField(max_length=128) #australian federal election'
    announced_date= models.DateField(blank=True, null=True)
    election_date = models.DateField(blank=True, null=True)
    
    def __unicode__(self):
        return self.name

class Contest(BaseModel):
    name = models.ForeignKey(Electorate) #warringah'
    participants = models.ManyToManyField(Politician, through='ContestParticipant')
    election = models.ForeignKey(Election)

    def __unicode__(self):
        return self.name

class ContestParticipant(BaseModel):
    CONTEST_STATUS = (
        (u'won', u'Won'),
        (u'lost', u'Lost'),
        (u'contesting', u'Contesting'),
    )
    politician = models.ForeignKey(Politician)
    contest = models.ForeignKey(Contest)
    party = models.ForeignKey(Party) # name of the party you are representing in this election
    contest_status = models.CharField(max_length=10, choices=CONTEST_STATUS)

    def __unicode__(self):
        return self.name


forum/models/question.py
from base import *
from tag import Tag
from django.utils.translation import ugettext as _

question_view = django.dispatch.Signal(providing_args=['instance', 'user'])

class QuestionManager(NodeManager):
    def search(self, keywords):
        return False, self.filter(models.Q(title__icontains=keywords) | models.Q(body__icontains=keywords))

class Question(Node):
    class Meta(Node.Meta):
        proxy = True

    answer_count = DenormalizedField("children", ~models.Q(state_string__contains="(deleted)"), node_type="answer")
    accepted_count = DenormalizedField("children", ~models.Q(state_string__contains="(deleted)"), node_type="answer", marked=True)
    favorite_count = DenormalizedField("actions", action_type="favorite", canceled=False)

    friendly_name = _("question")
    objects = QuestionManager()

    # gets the current status of the promise
    @property
    def current_status(self):
        if (self.accepted_answers.count() > 0): 
            return self.accepted_answers.order_by('-date_promised')[0].get_status_display
    
        return "Not yet rated"
    
    @property
    def currentStatusId(self):
        if (self.accepted_answers.count() > 0): 
            return self.accepted_answers.order_by('-date_promised')[0].status
    
        return "not_yet_rated"
    
    @property
    def current_status_headline(self):
        if (self.accepted_answers.count() > 0): 
            return self.accepted_answers.order_by('-date_promised')[0].body
    
        return 0 

    @property
    def closed(self):
        return self.nis.closed

    @property    
    def view_count(self):
        return self.extra_count

    @property
    def headline(self):
        if self.nis.deleted:
            return _('[deleted] ') + self.title

        if self.nis.closed:
            return _('[closed] ') + self.title

        return self.title

    @property
    def accepted_answers(self):
        return self.answers.filter(~models.Q(state_string__contains="(deleted)"), marked=True)

    @models.permalink    
    def get_absolute_url(self):
        return ('question', (), {'id': self.id, 'slug': django_urlquote(slugify(self.title))})

    def get_revision_url(self):
        return reverse('question_revisions', args=[self.id])

    def get_related_questions(self, count=10):
        cache_key = '%s.related_questions:%d:%d' % (settings.APP_URL, count, self.id)
        related_list = cache.get(cache_key)

        if related_list is None:
            related_list = Question.objects.filter_state(deleted=False).values('id').filter(tags__id__in=[t.id for t in self.tags.all()]
            ).exclude(id=self.id).annotate(frequency=models.Count('id')).order_by('-frequency')[:count]
            cache.set(cache_key, related_list, 60 * 60)

        return [Question.objects.get(id=r['id']) for r in related_list]


def question_viewed(instance, **kwargs):
    instance.extra_count += 1
    instance.save()

question_view.connect(question_viewed)


class QuestionSubscription(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Node)
    auto_subscription = models.BooleanField(default=True)
    last_view = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        app_label = 'forum'


class QuestionRevision(NodeRevision):
    class Meta:
        proxy = True
        

forum/models/tag.py
from base import *

from django.utils.translation import ugettext as _
import django.dispatch

class ActiveTagManager(models.Manager):
    def get_query_set(self):
        return super(ActiveTagManager, self).get_query_set().exclude(used_count__lt=1)


class Tag(BaseModel):
    name            = models.CharField(max_length=255, unique=True)
    created_by      = models.ForeignKey(User, related_name='created_tags')
    marked_by       = models.ManyToManyField(User, related_name="marked_tags", through="MarkedTag")
    # Denormalised data
    used_count = models.PositiveIntegerField(default=0)

    active = ActiveTagManager()

    class Meta:
        ordering = ('-used_count', 'name')
        app_label = 'forum'

    def __unicode__(self):
        return self.name

    def add_to_usage_count(self, value):
        if self.used_count + value < 0:
            self.used_count = 0
        else:
            self.used_count = models.F('used_count') + value

    @models.permalink
    def get_absolute_url(self):
        return ('tag_questions', (), {'tag': self.name})

class MarkedTag(models.Model):
    TAG_MARK_REASONS = (('good', _('interesting')), ('bad', _('ignored')))
    tag = models.ForeignKey(Tag, related_name='user_selections')
    user = models.ForeignKey(User, related_name='tag_selections')
    reason = models.CharField(max_length=16, choices=TAG_MARK_REASONS)

    class Meta:
        app_label = 'forum'

forum/forms/admin.py
import socket
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.admin.widgets import FilteredSelectMultiple, AdminDateWidget
from qanda import TitleField, EditorField
from forum import settings
from forum.models.node import NodeMetaClass
from forum.models import User

class IPListField(forms.CharField):
    def clean(self, value):
        ips = [ip.strip() for ip in value.strip().strip(',').split(',')]
        iplist = []

        if len(ips) < 1:
            raise forms.ValidationError(_('Please input at least one ip address'))

        for ip in ips:
            try:
                socket.inet_aton(ip)
            except socket.error:
                raise forms.ValidationError(_('Invalid ip address: %s' % ip))

            if not len(ip.split('.')) == 4:
                raise forms.ValidationError(_('Please use the dotted quad notation for the ip addresses'))

            iplist.append(ip)

        return iplist

class MaintenanceModeForm(forms.Form):
    ips = IPListField(label=_('Allow ips'),
                      help_text=_('Comma separated list of ips allowed to access the site while in maintenance'),
                      required=True,
                      widget=forms.TextInput(attrs={'class': 'longstring'}))

    message = forms.CharField(label=_('Message'),
                              help_text=_('A message to display to your site visitors while in maintainance mode'),
                              widget=forms.Textarea)


TEMPLATE_CHOICES = (
('default', _('Default')),
('sidebar', _('Default with sidebar')),
('none', _('None')),
)

RENDER_CHOICES = (
('markdown', _('Markdown')),
('html', _('HTML')),
('escape', _('Escaped'))
)

class UrlFieldWidget(forms.TextInput):
    def render(self, name, value, attrs=None):
        if not value:
            value = ''

        return """
                <input class="url_field" type="text" name="%(name)s" value="%(value)s" />
                <a class="url_field_anchor" target="_blank" href="%(app_url)s%(script_alias)s"></a>
            """  % {'name': name, 'value': value, 'app_url': settings.APP_URL,
                    'script_alias': settings.FORUM_SCRIPT_ALIAS}


class PageForm(forms.Form):
    def __init__(self, page, *args, **kwargs):
        if page:
            initial = page.extra
            initial.update(dict(title=page.title, content=page.body))
            super(PageForm, self).__init__(initial=initial, *args, **kwargs)
        else:
            super(PageForm, self).__init__(*args, **kwargs)


    title  = forms.CharField(label=_('Title'), max_length=255, widget=forms.TextInput(attrs={'class': 'longstring'}),
                             initial='New page')
    path  = forms.CharField(label=_('Page URL'), widget=UrlFieldWidget, initial='pages/new/')

    content = forms.CharField(label=_('Page Content'), widget=forms.Textarea(attrs={'rows': 30}))
    mimetype = forms.CharField(label=_('Mime Type'), initial='text/html')

    render = forms.ChoiceField(widget=forms.RadioSelect, choices=RENDER_CHOICES, initial='markdown',
                               label=_('Render Mode'))

    template = forms.ChoiceField(widget=forms.RadioSelect, choices=TEMPLATE_CHOICES, initial='default',
                                 label=_('Template'))
    sidebar = forms.CharField(label=_('Sidebar Content'), widget=forms.Textarea(attrs={'rows': 20}), required=False)
    sidebar_wrap = forms.BooleanField(label=_("Wrap sidebar block"), initial=True, required=False)
    sidebar_render = forms.ChoiceField(widget=forms.RadioSelect, choices=RENDER_CHOICES, initial='markdown',
                                       label=_('Sidebar Render Mode'))

    comments = forms.BooleanField(label=_("Allow comments"), initial=False, required=False)

from forum.forms.auth import SimpleRegistrationForm
from forum.forms.general import SetPasswordForm


class CreateUserForm(SimpleRegistrationForm, SetPasswordForm):
    validate_email = forms.BooleanField(required=False, label=_('send validation email'))

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['username', 'email', 'validate_email', 'password1', 'password2']
        self.fields['email'].label = _('email address')


    

forum/skins/poliwatch/templates/401.html
{% extends "base_content.html" %}
{% load i18n %}
{% block title %}{% trans "Not logged in" %}{% endblock %}
{% block meta %}
    <!-- <meta http-equiv="refresh" content="5;url={% url auth_signin %}"> -->
{% endblock %}
{% block forestyle%}
    <style type="text/css">
 		form input { margin-right: 5px; }
	</style>
{% endblock %}
{% block forejs %}
       <script type="text/javascript">
        $().ready(function(){
            window.setInterval(function() {
                $('#redirect_loader').html($('#redirect_loader').html() + '.')
            }, 800);

            window.setTimeout(function() {
                window.location = "{% url auth_signin %}";
            }, 5000);
        });

        </script>
{% endblock %}
{% block content %}
<div id="main-bar" class="headNormal">
    {% trans "Not logged in" %}
</div>
<div id="main-body" class="">
    <div style="padding:5px 0px 10px 0;line-height:25px;">
        <h3>{% trans "You are not logged in..." %}</h3>
        <div style="margin-top:5px">
            {% trans "...and the resource you're trying to access is pretocted." %}
            <p>
                {% trans "Redirecting to the login page." %}<span id="redirect_loader"></span>
            </p>
            <p>
                {% trans "If you're not automatically redirected in 5 seconds, please click" %}
                <a href="{% url auth_signin %}">{% trans "here" %}</a>.
            </p>
        </div>
    </div>

</div>
{% endblock %}

forum/skins/poliwatch/templates/answer_edit.html
{% extends "base.html" %}
<!-- template answer_edit.html -->
{% load i18n %}
{% load extra_tags %}
{% block title %}{% spaceless %}{% trans "Edit answer" %}{% endspaceless %}{% endblock %}
{% block forejs %}
        <script type='text/javascript' src='{% media  "/media/js/wmd/showdown.js" %}'></script>
		<script type='text/javascript' src='{% media  "/media/js/jquery-ui.min.js" %}'></script>
        <script type='text/javascript' src='{% media  "/media/js/wmd/wmd.js" %}'></script>
		<link rel="stylesheet" type="text/css" href="{% media  "/media/style/ui-lightness/jquery-ui-1.7.3.custom.css" %}" />
        <link rel="stylesheet" type="text/css" href="{% media  "/media/js/wmd/wmd.css" %}" />
        <script type="text/javascript">
            $(function(){
                $('.vDateField').datepicker({
                    dateFormat: 'dd/mm/yy',
                    constrainInput: 'true',
                    maxDate: ' 0',
                })
            });
        </script>
        <script type="text/javascript">
           	setup_wmd({
                "input": "editor",
                "button_bar": "wmd-button-bar",
				"buttons": true,
                "preview": "previewer",
            });
			setup_wmd({
                "input": "sources",
				"button_bar": "wmd-button-bar-sources",				
				"buttons": true,
				"preview": "previewer-sources",
            });				
        </script>		
		<script type="text/javascript">
        
        $().ready(function(){
            $("#nav_questions").attr('className',"on");
            $('#editor').TextAreaResizer();


            //toggle preview of editor
            var display = true;
            var txt = "{% trans "hide preview" %}";
            $('#pre-collapse').text(txt);
            $('#pre-collapse').bind('click', function(){
                txt = display ? "{% trans "show preview" %}" : "{% trans "hide preview" %}";
                display = !display;
                $('#previewer').toggle();
				$('#previewer-sources').toggle();
                $('#pre-collapse').text(txt);
            });


            $('#id_revision').unbind().change(function(){
                $("#select_revision").click();
            });


            answer = $("textarea#editor")[0].value;
        });


        function submitClicked(e, f) {
            if(!(browserTester('chrome') || browserTester('safari'))) {
                $("input.submit")[0].disabled=true;
                $("input.submit")[1].disabled=true;
            }
            window.removeEventListener('beforeunload', beforeUnload, true);
            if (f) {
                f.submit();
            }
        }

        function beforeUnload(e) {
            if($("textarea#editor")[0].value != answer) {
                 return yourWorkWillBeLost(e);
            }
        }
        window.addEventListener('beforeunload', beforeUnload, true);

        var answer = "";
        </script>
{% endblock %}
        
{% block content %}
<div id="main-bar" class="headNormal">
    {% trans "Edit answer" %} [<a href="{{ answer.question.get_absolute_url }}#{{ answer.id }}">{% trans "back" %}</a>]
</div>
<div id="main-body" class="ask-body">
    <div id="askform">
        <form id="fmedit" action="{% url edit_answer answer.id %}" method="post" >
            <label for="id_revision" ><strong>{% trans "revision" %}:</strong></label> <br/> 
            {% if revision_form.revision.errors %}{{ revision_form.revision.errors.as_ul }}{% endif %}
            <div>
            {{ revision_form.revision }} <input type="submit" style="display:none" id="select_revision" name="select_revision" value="{% trans "select revision" %}">
            </div>
			<div class="form-item">
                <label for="id_title" ><strong>{{ form.title.label_tag }}:</strong></label> <span class="form-error"></span><br/> 
                {{ form.title }} {{ form.title.errors }}  
                <div class="title-desc">
                    {{ form.title.help_text }}
                </div>     
            </div>
            
            <div class="form-item">
                <label for="id_status" ><strong>{{ form.status.label_tag }}:</strong></label> <span class="form-error"></span><br/>
                {{ form.status }} {{ form.status.errors }}
                <div class="title-desc">
                    {{ form.status.help_text }}
                </div>
            </div>

            <!-- Date Promised -->
            <div class="form-item">
                <strong>{{ form.date_promised.label_tag }}:</strong> {% trans "(required)" %} <span class="form-error"></span><br/>
                {{ form.date_promised }}  {{ form.date_promised.errors }}
            </div>

            <div class="form-item">
                <div id="wmd-button-bar" class="wmd-button-bar"></div>
                {{ form.text }}
                <span class="form-error"></span>
				<label for="sources" ><strong>{{ form.sources.label_tag }}:</strong></label>
				 <div class="title-desc">
                    {{ form.sources.help_text }}
                </div>
				<div id="wmd-button-bar-sources" class="wmd-button-bar"></div>
				{{ form.sources }} {{form.sources.errors }}
                <div class="preview-toggle"><span id="pre-collapse" 
					title="{% trans "Toggle the real time Markdown editor preview" %}">{% trans "toggle preview" %}</span>
				{% if settings.WIKI_ON %}
                    <div style="float:right;">
                        {{ form.wiki }} <span style="color:#000;cursor:help" title="{{form.wiki.help_text}}">{{ form.wiki.label_tag }} </span>
                    </div>
                    {% endif %}
                </div>
                <div id="previewer" class="wmd-preview"></div>
				<div id="previewer-sources" class="wmd-preview"></div>
            </div>
            
            <strong>{{ form.summary.label_tag }}</strong> <br/>
            {{ form.summary }}  {{ form.summary.errors }}
            <div class="title-desc">
                {{ form.summary.help_text }}
            </div>
            <input type="button" value="{% trans "Save edit" %}" class="submit" onclick="submitClicked(event, this.form)" />
            <input type="button" value="{% trans "Cancel" %}" class="submit" onclick="submitClicked(event, this.form);history.back(-1);" />
        </form>
    </div>
</div>

<div id="dialog-form" title="Add source" style="display:none">
	<p class="validateTips">Below is a quick website Harvard-style reference template.</p>	
	<form>
	<fieldset>
		<label for="name">Author</label>
		<input type="text" name="author" id="author" class="text ui-widget-content ui-corner-all" />
		<label for="date">Date</label>
		<input type="text" name="date" id="date" value="" class="text ui-widget-content ui-corner-all" />
		<label for="title">Title</label>
		<input type="text" name="title" id="title" value="" class="text ui-widget-content ui-corner-all" />
		<label for="sponsor">Sponsor of website</label>
		<input type="text" name="sponsor" id="sponsor" value="" class="text ui-widget-content ui-corner-all" />
		<label for="accessed">Date accessed</label>
		<input type="text" name="accessed" id="accessed" value="" class="text ui-widget-content ui-corner-all" />
		<label for="accessed">Link</label>
		<input type="text" name="link" id="link" value="" class="text ui-widget-content ui-corner-all" />
		<input type="hidden" name="isCancel" id="isCancel" value="false"/>	
	</fieldset>
	</form>
</div>

<script type="text/javascript">
$(document).ready(function() {
	// initialize jquery ui dialog
	$("#dialog-form").dialog({
		autoOpen: false,
		height: 550,
		width: 350,
		modal: true,
		buttons: {
			Cancel: function() {				
				$("#isCancel").val('true');
				$(this).dialog("close");				
			},
			Add: function() {
				$("#isCancel").val('false');								
				$(this).dialog("close");
			}
		},
		close: function() {							
		}
	});				
});
</script>

{% endblock %}

{% block sidebar %}
{% include "answer_edit_tips.html" %}
{% endblock %}

{% block endjs %}
{% endblock %}
<!-- end template answer_edit.html -->

forum/skins/poliwatch/templates/badges.html
{% extends "base.html" %}
<!-- template badges.html -->
{% load extra_tags %}
{% load humanize %}
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Badges summary" %}{% endspaceless %}{% endblock %}
{% block content %}
<div class="headlineA">
        <span class="headMedals">{% trans "Badges" %}</span>
</div>
<div class="badges" id="main-body" style="width:100%">
    <p>
	{% trans "Community gives you awards for your questions, answers and votes." %}
	{% blocktrans %}Below is the list of available badges and number of times each type of badge has been awarded.
    {% endblocktrans %}
    </p>
    <div id="medalList">
        {% for badge in badges %}
        <div style="clear:both;line-height:30px">
            <div style="float:left;min-width:30px;text-align:right;height:30px">
            {% for a in mybadges %}
                {% ifequal a.badge_id badge.id %}
                 <span style="font-size:175%; padding-right:5px; color:#5B9058;">&#10004;</span>
                {% endifequal %}
            {% endfor %}
            </div>
            <div style="float:left;width:230px;">
                <a href="{{badge.get_absolute_url}}" title="{{ badge.get_type_display }} : {{ badge.description }}" class="medal"><span class="badge{{ badge.type }}">&#9679;</span>&nbsp;{{ badge.name }}</a><strong> &#215; {{ badge.awarded_count|intcomma }}</strong>
            </div>
            <p style="float:left;margin-top:8px;">
                {{ badge.description }}
            </p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block sidebar %}

<div class="boxC">
    <h3>{% trans "Community badges" %}</h3>
    <div class="body">
    <p>
        <a style="cursor:default;" title="{% trans "gold badge: the highest honor and is very rare" %}" class="medal"><span class="badge1">&#9679;</span>&nbsp;{% trans "gold" %}</a>
    </p>
    <p>
	{% trans "gold badge description" %}
    </p>
    <p>
        <a style="cursor:default;" 
			title="{% trans "silver badge: occasionally awarded for the very high quality contributions" %}" 
			class="medal"><span class="badge2">&#9679;</span>&nbsp;{% trans "silver" %}</a>
    </p>
    <p>
	{% trans "silver badge description" %}
    </p>
    <p>
        <a style="cursor:default;" title="{% trans "bronze badge: often given as a special honor" %}" class="medal">
		<span class="badge3">&#9679;</span>&nbsp;{% trans "bronze" %}</a>
    </p>
    <p>
	{% trans "bronze badge description" %}
    </p>
    </div>
</div>
{% endblock %}
<!-- end template badges.html -->